export const RENTALS = [
    {
        id: 0,
        name: "modern getaway",
        image: "/assets/images/future.jpg",
        location: 'rural',
        description: "Löksås ipsum nu tiden genom färdväg strand oss trevnadens.",
        type: "rental",
    },
    {
        id: 1,
        name:"cabin",
        image: "/assets/images/cabin.jpg",
        location: 'rural',
        description: "Vi vad vi det rännil vidsträckt, bäckasiner omfångsrik ta från verkligen tiden",
        type: "rental",
    },
    {
        id: 2,
        name:"snowy cabin",
        image: "/assets/images/cabin-snow.jpg",
        location: 'rural',
        description: "Hav gör icke omfångsrik helt faktor mot och omfångsrik",
        type: "rental",
    },
    {
        id: 3,
        name:"cabin by the fjord",
        image: "/assets/images/cabin-fjord.jpg",
        elevation: 42,
        location: 'rural',
        description: "Tid genom varit träutensilierna i blivit dimma både",
        type: "rental",
    },
    {
        id: 4,
        name: "hus ved bukta",
        image: "/assets/images/houses.jpg",
        location: 'urban',
        description: "Om tid vi där söka rot räv gamla dimma sax",
        type: "rental",
    },
    {
        id: 5,
        name:"mountain view house",
        image: "/assets/images/town.jpg",
        elevation: 877,
        location: 'urban',
        description: "Ser dock åker sig färdväg bäckasiner oss från faktor häst",
        type: "rental",
    },
    {
        id: 6,
        name:"oslo alley house",
        image: "/assets/images/city.jpg",
        location: 'urban',
        description: "Bland vi faktor denna vad miljoner samma jäst så vad åker söka",
        type: "rental",
    },
    {
        id: 7,
        name:"trondheim getaway",
        image: "/assets/images/city-snow.jpg",
        location: 'urban',
        description: "Vid att verkligen regn gör träutensilierna nya vad sjö dimma björnbär nya",
        type: "rental",
    }
];