export const TOURS = [
    {
        id: 0,
        name: "forest excursion",
        image: "/assets/images/forest.jpg",
        elevation: 1233,
        featured: false,
        description: "travel deep into the norwegian forest",
        cName: "normal",
        type: "tour",
    },
    {
        id: 1,
        name:"stave churches",
        image: "/assets/images/stave.jpg",
        elevation: 877,
        featured: false,
        description: "see the historic medieval stave churches",
        cName: "normal",
        type: "tour",
    },
    {
        id: 2,
        name:"true norwegian black metal",
        image: "/assets/images/metal.jpg",
        elevation: 2901,
        featured: false,
        description: "visit the heart of winter",
        cname: "metal",
        type: "tour",
    },
    {
        id: 3,
        name:"coastal excursion",
        image: "/assets/images/flag-ocean.jpg",
        elevation: 42,
        featured: true,
        description: "explore the coast",
        cName: "normal",
        type: "tour",
    }
];